
current_version: 190929

cutout_folder: "../cutouts/"

octant_folder: "../octants/"

weather_years: [2011,2012,2013,2014]

tech_years: [2020,2030,2040,2050]

tech_years_default: 2030

cost_year_assumptions: 2020 #year used in original tech_data assumptions
cost_year: 2020 #year used in website
inflation: 2



float_upper_limit: 2.e+7

tech_data_commit: "4270332f70089166abd24b73b058f370bb126cb8"
trace_commit: "55e71c86d36869079b46377ce7ef16a46afa1d99"


renewable:
  onwind:
    method: wind
    resource:
      turbine: Vestas_V112_3MW
  solar:
    method: pv
    resource:
      panel: CSi
      orientation:
        slope: 35.
        azimuth: 180.
    correction_factor: 1.

#LHV
mwh_per_t:
  methanol: 5.54

#LHV at 20 C
mwh_per_m3:
  methanol: 4.4

octant_compression:
  complevel: 4
  least_significant_digit: 5


balances_to_display: ["electricity","hydrogen"]

preferred order: ["wind","solar","battery storage","battery inverter","hydrogen storage","hydrogen storing compressor","hydrogen electrolyser","seawater desalination","hydrogen turbine"]


colors:
  wind : "#3B6182"
  solar: "#FFFF00"
  battery: "#999999"
  battery_charge: "#999999"
  battery_discharge: "#999999"
  battery discharger: "#999999"
  battery_power: "#999999"
  battery inverter: "#999999"
  battery_energy: "#666666"
  battery storage: "#666666"
  hydrogen_turbine: red
  hydrogen turbine: red
  hydrogen_electrolyser: cyan
  hydrogen electrolyser: cyan
  hydrogen_energy: magenta
  hydrogen storage: magenta
  hydrogen storing compressor: "#ff66ff"
  hydrogen_compressor: "#ff66ff"
  hydrogen storing decompressor: "#660066"
  lh2 shipping: green
  dispatchable1: orange
  dispatchable2: lime
  load: black
  hydrogen_load: purple
  hydrogen load: purple
  dac: "#999966"
  co2 storage: "#666633"
  heat pump: red
  methanol synthesis: "#F08080"
  methanol storage: black
  Allam cycle: pink
  seawater desalination: "#000099"
